data_dir: '/home/imperator/Datasets'
data_name: 'mnist-dvs'

org_WIDTH: 128
org_HEIGHT: 128
time_window: 100000

WIDTH: 128
HEIGHT: 128
T: 128

batch_size: 64
num_workers: 8

num_classes: 10

radius: 3
num_bits: 8

# Trainer
lr: 0.001
weight_decay: 1e-4
max_epochs: 100
log_every_n_steps: 1
gradient_clip_val: 0.0
accumulate_grad_batches: 1


