data_dir: '/home/lsriw/Datasets'
data_name: 'ncaltech101'

org_WIDTH: 240
org_HEIGHT: 180
time_window: 50000

WIDTH: 256
HEIGHT: 256
T: 256

batch_size: 32
num_workers: 8

num_classes: 100

radius: 3

# Trainer
lr: 0.0001
weight_decay: 1e-4
max_epochs: 100
log_every_n_steps: 1
gradient_clip_val: 0.0
accumulate_grad_batches: 1

# Augmentation
rotate_angle: 0
hflip: 0.5

dropout_rate: 0.0

# Model
conv1:
  in_channels: 3
  out_channels: 18
  num_bits: 8
  bias: False

pool1:
  grid: [4, 4, 4]

conv2:
  in_channels: 20
  out_channels: 36
  num_bits: 8
  bias: False

conv3:
  in_channels: 38
  out_channels: 72
  num_bits: 8
  bias: False

pool2:
  grid: [2, 2, 2]

conv4:
  in_channels: 74
  out_channels: 72
  num_bits: 8
  bias: False

conv5:
  in_channels: 74
  out_channels: 135
  num_bits: 8
  bias: False

pool_out:
  pool_size: 8
  max_dim: 32

linear1:
  in_features: 2160 # 135*4**2
  out_features: 1024
  num_bits: 8
  bias: True

linear2:
  in_features: 1024
  out_features: 100
  num_bits: 8
  bias: True